baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'
copyright = ''

# Supprt Posts and Tags
# [[menus.main]]
# name = 'Posts'
# pageRef = '/posts'
# weight = 20

# [[menus.main]]
# name = 'Tags'
# pageRef = '/tags'
# weight = 30


[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
